version: "3"
services:
  app1:
    image: amezdoc/student-api:main
    restart: always
    environment:
      - MONGO_URI=mongodb://mongo:27017/students
    depends_on:
      - mongo
    networks:
      - student_net

  app2:
    image: amezdoc/student-api:main
    restart: always
    environment:
      - MONGO_URI=mongodb://mongo:27017/students
    depends_on:
      - mongo
    networks:
      - student_net

  mongo:
    image: mongo:4.4
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    networks:
      - student_net

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app1
      - app2
    networks:
      - student_net

networks:
  student_net:
    driver: bridge
