name: CI Pipeline

on:
  push:
    branches:
      - main
    paths:
      - "src/**" # Runs only if changes are made in the "src" directory
  workflow_dispatch: # Allows manual triggering

jobs:
  build-and-deploy:
    runs-on: self-hosted # Runs on your local machine

    steps:
      - name: Check installed modules
        run: ls -l node_modules | grep winston || echo "winston is missing!"
        
      - name: Install dependencies
        run: npm ci 
        
      - name: Checkout code
        uses: actions/checkout@v4 # Fetches the latest code

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 # Enables better Docker builds

      - name: Build API
        run: make build # Uses Makefile to build the Docker image

      - name: Run tests
        run: make test # Runs tests inside the container

      - name: Perform code linting
        run: make lint # Runs linter inside the container

      - name: Log in to DockerHub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - name: Push Docker Image
        run: make push # Pushes the Docker image to DockerHub
