name: CI Pipeline

on:
  push:
    branches:
      - main
    paths:
      - "src/**" # Runs only if changes are made in the "src" directory
  workflow_dispatch: # Allows manual triggering

jobs:
  build-and-deploy:
    runs-on: self-hosted # Runs on your local machine

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Fetches the latest code
        
      - name: Check installed modules
        run: ls -l node_modules | grep winston || echo "winston is missing!"
        
      - name: Install dependencies
        run: npm ci 
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 # Enables better Docker builds

      - name: Build API
        run: make docker-build. # Uses Makefile to build the Docker image
        
      - name: Start MongoDB
        run: make mongo-start
        
      - name: Run tests
        run: make docker-test. # Runs tests inside the container
        
      - name: Stop MongoDB
        run: make mongo-stop # Stops MongoDB to clean up

      - name: Perform code linting
        run: make docker-lint. # Runs linter inside the container

      - name: Log in to DockerHub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - name: Push Docker Image
        run: make push # Pushes the Docker image to DockerHub
