name: CI Pipeline

on:
  push:
    branches:
      - main
    paths:
      - "src/**"
  workflow_dispatch: # Allows manual triggering

jobs:
  build-and-deploy:
    name: push docker image to dockerhub
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies (Cross-Platform)
        shell: bash
        run: |
          echo "Detected OS: $RUNNER_OS"
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            echo "Installing dependencies on Windows"
            if [ -f package-lock.json ]; then
              npm ci
            else
              npm install
            fi
          else
            echo "Installing dependencies on Linux/macOS"
            if [ -f package-lock.json ]; then
              npm ci
            else
              npm install
            fi
          fi  # <-- Fixed missing "fi"

      - name: Set up Docker network
        run: docker network create student_network || true
        shell: bash

      - name: Start MongoDB container
        run: |
          docker ps -a --filter "name=mongodb" --format "{{.ID}}" | xargs -r docker rm -f
          docker run -d --network student_network --name mongodb mongo:latest
        shell: bash

      - name: Build Student CRUD API container
        run: docker build -t student_crud_api .

      - name: Run Jest tests inside the container
        run: |
          docker run --network student_network -e MONGO_URI="mongodb://mongodb:27017/students" student_crud_api sh -c "
          npm install --legacy-peer-deps &&  
          npx jest --runInBand --forceExit --detectOpenHandles
          "

      # - name: Stop and remove MongoDB container
      #   run: docker stop mongodb && docker rm mongodb

      - name: Perform code linting
        run: npm run lint || echo "Linting failed!"
        shell: bash

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: amezdoc/student-api:1.0.0

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
