name: Docker Image CI

on:
  push:
    paths:
      - 'src/**'
      - 'Dockerfile'
      - 'Makefile'
    branches:
      - main
  workflow_dispatch: # Allow manual triggers

jobs:
  build:
    runs-on: self-hosted  # Use self-hosted GitHub runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Run linting
        run: npx eslint .

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t student-api:latest .
          docker tag student-api:latest your-dockerhub-username/student-api:latest
          docker push your-dockerhub-username/student-api:latest
 
 
